### ISSUE TITLE
Manage the package import placement

### ISSUE THREAD

**Issue by RikLakhe** [PramodThapa/practitioner-managment#15]
https://github.com/PramodThapa/practitioner-managment/blob/ebcefd02951d3b534bca46d4c0aa3c803a01c971/frontend/src/main.tsx#L1

1st import from node_modules
<blank line>
2nd import from src project itself

**Comment by PramodThapa** [comment]
Fixed in 

https://github.com/PramodThapa/practitioner-managment/pull/21/commits/e344241010e26f1df4f67b740b6df65673edc596
